<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Formulaire</title>
        <link rel="stylesheet" href="CSS/bootstrap.min.css" />
        <link rel="stylesheet" href="CSS/formulaire.css" />
    </head>
    <body>
      <header>
        <nav>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="formulaire.phtml">Add</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
        <div class="banniere_image">
        </div>
      </header>
      <div class= "body">
        <form action="/ajout" method="post">
          <h1>add manga</h1>
          <div>
            <label for="name">Name:</label>
            <input type="text" id="name" name="Name">
          </div>

          <div>
            <label for="Autor">Autor:</label>
            <input type="text" id="Autor" name="Autor">
          </div>
          <div>
            <label for="date">Published:</label>
            <input type="number" id="Published" name="Published" min=0>
          </div>
          <div>
          <div>
            <label for="Volume">Volume:</label>
            <input type="number" id="Volume" name="Volume" min=0 >
          </div>
          <div>
            <label for="Status">status:</label>
            <input type="text" id="Status" name="Status">
          </div>
          <div>
            <label for="Like">Description:</label>
            <TEXTAREA name="Description" rows=4 cols=40></TEXTAREA>
          </div>

          <div class="button">
            <button type="submit">Validate</button>
          </div>
          <div>
          </div>
        </form>
      </div>
    </body>
</html>
