<!DOCTYPE html>
<html>
    <head>
        <!-- En-tête de la page -->
	    <meta charset="utf-8" />
      <link rel="stylesheet" href="CSS/bootstrap.min.css" />
	     <link rel="stylesheet" href="CSS/home.css" />
	    <title>Home</title>
    </head>
    <body >
        <!-- Corps de la page -->
        <div class= "bloc_page">
	        <header>
                <nav>
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="formulaire">Add</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </nav>
                <div class="banniere_image">
                </div>
            </header>
	        <h1>
			  All mangas
			</h1>
			<article>
				<?php foreach ($mangalist as $manga_list): ?>
					<div class="form">
						<table width="200" border="0">
							<tr>
							  <th scope="col">
							  	<?php if($manga_list->Name=="Naruto"){?>
							  		<img alt="Naruto" src="image/Naruto.jpeg" width="250" height="300"/></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Attack On Titan"){?>
							  		<img alt="Attack_On_Titan" src="image/Attack_On_Titan.jpeg" width="250" height="300"/></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Bleach"){?>
							  		<img alt="Bleach" src="image/Bleach.jpeg" width="250" height="300"/></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Tokyo Ghoul: Re"){?>
							  		<img alt="Tokyo_Ghoul_Re" src="image/Tokyo_Ghoul_Re.jpeg" width="250" height="300"/></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Nanatsu no Taizai"){?>
							  		<img alt="Nanatsu_no_Taizai" src="image/Nanatsu_no_Taizai.png" width="250" height="300" /></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Shokugeki no Soma"){?>
							  		<img alt="Shokugeki_no_Soma" src="image/Shokugeki_no_Soma.jpeg" width="250" height="300" /></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="One Piece"){?>
							  		<img alt="One_Piece" src="image/One_Piece.png" width="250" height="300" /></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Onepunch-Man"){?>
							  		<img style="cursor:pointer;"alt="one_punch_man" src="image/one_punch_man.jpeg" width="250" height="300"/></br>
							  	<?php } ?>
							  	<?php if($manga_list->Name=="Eyeshield 21"){?>
                                    <img alt="One_Piece" src="image/Eyeshield_21.jpeg" width="250" height="300"/></br>
                                <?php } ?>
								<form action= "show_one.phtml" methode="get">
								  	<?php echo $manga_list->Name;?></a></br>
								  	<input type="hidden" name= "id" value= "<?php echo $manga_list->id;?>"></input>
								  	<input style="cursor:pointer;" type="submit" value="show ">
								</form>
							  </th>
							</tr>
						</table>
					</div>
				<?php endforeach; ?>
			</article>
		</div>
    </body>
</html>
