<!DOCTYPE html>
<html>
    <head>
        <!-- En-tête de la page -->
        <meta charset="utf-8" />
        <link rel="stylesheet" href="CSS/bootstrap.min.css" />
        <link rel="stylesheet" href="CSS/show_one.css" />
        <title>Titre</title>
    </head>
    <body>
        <!-- Corps de la page -->
        <header>
            <nav>
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="formulaire.phtml">Add</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </nav>
            <div class="banniere_image">
            </div>
        </header>
        <article>
            <?php $a=0; ?>
            <?php foreach ($mangalist as $manga_list): ?>
                <?php if($a==0){ ?>
                    <h1>
                      <?php echo $mangalist->Name; ?>
                    </h1>
                    <div class="form">
                        <table width="200" border="0">

                            <tr>
                              <th scope="col">
                                <?php if($mangalist->Name=="Naruto"){?>
                                    <img alt="Naruto" src="image/Naruto.jpeg" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Attack On Titan"){?>
                                    <img alt="Attack_On_Titan" src="image/Attack_On_Titan.jpeg" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Bleach"){?>
                                    <img alt="Bleach" src="image/Bleach.jpeg" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Tokyo Ghoul: Re"){?>
                                    <img alt="Tokyo_Ghoul_Re" src="image/Tokyo_Ghoul_Re.jpeg" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Nanatsu no Taizai"){?>
                                    <img alt="Nanatsu_no_Taizai" src="image/Nanatsu_no_Taizai.png" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Shokugeki no Soma"){?>
                                    <img alt="Shokugeki_no_Soma" src="image/Shokugeki_no_Soma.jpeg" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="One Piece"){?>
                                    <img alt="One_Piece" src="image/One_Piece.png" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Onepunch-Man"){?>
                                    <img alt="one_punch_man" src="image/one_punch_man.jpeg" /></br>
                                <?php } ?>
                                <?php if($mangalist->Name=="Eyeshield 21"){?>
                                    <img alt="One_Piece" src="image/Eyeshield_21.jpeg" /></br>
                                <?php } ?>
                              </th>
                              <th>
                                <p>Autor :<?php echo $mangalist->Autor;?></br></p>
                                <p>Published : <?php echo $mangalist->Published;?></br></p>
                                <p>Volume : <?php echo $mangalist->Volume;?></br></p>
                                <p>Status : <?php echo $mangalist->Status;?></br></p>
                                <p>Description:</p>
                                <p> <?php echo $mangalist->Description;?></br></p>
                              </th>
                              <th class= "line">
                                <form action= "formulaire_edit.phtml" methode="get">
                                    <input type="hidden" name= "id" value= "<?php echo $mangalist->id;?>"></input>
                                    <input style="cursor:pointer;" type="submit" value="Edit ">
                                </form>
                                <form action= "delete" methode="get">
                                    <input type="hidden" name= "id" value= "<?php echo $mangalist->id;?>"></input>
                                    <input style="cursor:pointer;" type="submit" value="Delete">
                                </form>
                              </th>
                            </tr>
                        </table>
                    </div>
                    <?php $a=1;?>
            <?php } endforeach; ?>
        </article>
    </body>
</html>
